# Generated by Django 2.2.2 on 2019-06-17 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chan_chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pud_date',
            new_name='pub_date',
        ),
    ]
